# Generated by Django 6.0.2 on 2026-05-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_assistant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('file', 'File'), ('url', 'URL')], max_length=16)),
                ('file', models.FileField(blank=True, null=True, upload_to='datasets/')),
                ('source_url', models.URLField(blank=True, default='')),
                ('stored_path', models.CharField(blank=True, default='', max_length=255)),
                ('row_count', models.IntegerField(default=0)),
                ('status', models.CharField(default='processed', max_length=24)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='manual', max_length=32)),
                ('status', models.CharField(default='success', max_length=24)),
                ('details', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
