# Generated by Django 6.0.2 on 2026-05-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_assistant', '0002_datasetupload_ingestionjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetupload',
            name='ai_blueprint',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
