# Generated by Django 6.0.2 on 2026-07-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_assistant', '0004_dashboardstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
