# Generated by Django 6.0.2 on 2026-07-14 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_assistant', '0007_default_org_backfill'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetupload',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
