# Generated by Django 6.0.2 on 2026-07-14 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_assistant', '0008_datasetupload_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetupload',
            name='active_version_number',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='DatasetVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField()),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('source_type', models.CharField(choices=[('file', 'File'), ('url', 'URL')], max_length=16)),
                ('file', models.FileField(blank=True, null=True, upload_to='datasets/versions/')),
                ('source_url', models.URLField(blank=True, default='')),
                ('stored_path', models.CharField(blank=True, default='', max_length=255)),
                ('row_count', models.IntegerField(default=0)),
                ('ai_blueprint', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='analytics_assistant.datasetupload')),
            ],
            options={
                'ordering': ['dataset', '-version_number'],
                'unique_together': {('dataset', 'version_number')},
            },
        ),
    ]
