# Generated by Django 6.0.2 on 2026-07-14 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_workspaces(apps, schema_editor):
    user_app, user_model = settings.AUTH_USER_MODEL.split('.')
    User = apps.get_model(user_app, user_model)
    Workspace = apps.get_model('analytics_assistant', 'Workspace')
    DatasetUpload = apps.get_model('analytics_assistant', 'DatasetUpload')
    DashboardState = apps.get_model('analytics_assistant', 'DashboardState')
    ChatSession = apps.get_model('analytics_assistant', 'ChatSession')

    for user in User.objects.all():
        workspace, created = Workspace.objects.get_or_create(
            owner=user,
            defaults={'name': f"{user.username}'s Workspace"}
        )
        DatasetUpload.objects.filter(owner=user).update(workspace=workspace)
        DashboardState.objects.filter(user=user).update(workspace=workspace)
        ChatSession.objects.filter(user=user).update(workspace=workspace)


def reverse_backfill(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_assistant', '0009_datasetupload_active_version_number_datasetversion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='chatsession',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to='analytics_assistant.workspace'),
        ),
        migrations.AddField(
            model_name='dashboardstate',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_states', to='analytics_assistant.workspace'),
        ),
        migrations.AddField(
            model_name='datasetupload',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datasets', to='analytics_assistant.workspace'),
        ),
        migrations.RunPython(backfill_workspaces, reverse_backfill),
    ]
