# Generated by Django 6.0.2 on 2026-07-15 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_assistant', '0011_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetupload',
            name='connection_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='datasetupload',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasetupload',
            name='source_type',
            field=models.CharField(choices=[('file', 'File'), ('url', 'URL'), ('postgres', 'PostgreSQL')], max_length=16),
        ),
        migrations.AlterField(
            model_name='datasetversion',
            name='source_type',
            field=models.CharField(choices=[('file', 'File'), ('url', 'URL'), ('postgres', 'PostgreSQL')], max_length=16),
        ),
    ]
