# Generated by Django 6.0.2 on 2026-07-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_assistant', '0012_datasetupload_connection_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetupload',
            name='insights_cache',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='datasetversion',
            name='insights_cache',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
