# Generated by Django 6.0.2 on 2026-07-16 16:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_assistant', '0013_datasetupload_insights_cache_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetupload',
            name='source_type',
            field=models.CharField(choices=[('file', 'File'), ('url', 'URL'), ('postgres', 'PostgreSQL'), ('mysql', 'MySQL'), ('sqlite', 'SQLite'), ('sqlserver', 'SQL Server')], max_length=16),
        ),
        migrations.AlterField(
            model_name='datasetversion',
            name='source_type',
            field=models.CharField(choices=[('file', 'File'), ('url', 'URL'), ('postgres', 'PostgreSQL'), ('mysql', 'MySQL'), ('sqlite', 'SQLite'), ('sqlserver', 'SQL Server')], max_length=16),
        ),
        migrations.CreateModel(
            name='BackgroundJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=16)),
                ('connector', models.CharField(blank=True, default='', max_length=64)),
                ('progress', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=0)),
                ('result_metadata', models.JSONField(blank=True, default=dict)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('recurrence', models.CharField(choices=[('none', 'None'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_jobs', to=settings.AUTH_USER_MODEL)),
                ('dataset_upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='analytics_assistant.datasetupload')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='analytics_assistant.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
