# Generated by Django 6.0.2 on 2026-07-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_assistant', '0014_alter_datasetupload_source_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundjob',
            name='current_stage',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='datasetversion',
            name='cleaning_report',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='datasetversion',
            name='insights_cache',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
