# Generated by Django 6.0.2 on 2026-07-16 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_assistant', '0015_backgroundjob_current_stage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundjob',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='analytics_assistant.workspace'),
        ),
    ]
